version: '3.9'

# --------------------------------- Networks --------------------------------- #
networks:
  proxy:
    external:
      name: proxy
  socket_proxy:
    external:
      name: socket_proxy
  apps:
    external:
      name: apps
  default:
    driver: bridge

services:
  # ---------------------------------------------------------------------------- #
  #                                   Portainer                                  #
  # ---------------------------------------------------------------------------- #
  portainer:
    container_name: 'portainer'
    image: 'portainer/portainer-ce:latest'
    restart: 'unless-stopped'
    networks:
      - 'proxy'
      - 'socket_proxy'
      - 'apps'
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '$DOCKERDIR/portainer/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/:/host'
    environment:
      - 'TZ=$TZ'
    labels:
      traefik.docker.network: 'proxy'
      traefik.enable: 'true'
      traefik.http.routers.portainer.entrypoints: 'websecure'
      traefik.http.routers.portainer.rule: 'Host(`portainer.$DOMAINNAME`)'
      traefik.http.routers.portainer.service: 'portainer-svc'
      traefik.http.routers.portainer.tls: 'true'
      traefik.http.routers.portainer.tls.certresolver: 'wildcard-cloudflare'
      traefik.http.services.portainer-svc.loadbalancer.server.port: '9000'

  # ---------------------------------------------------------------------------- #
  #                         Glances - System Information                         #
  # ---------------------------------------------------------------------------- #
  glances:
    container_name: 'glances'
    image: 'jdreinhardt/glances:release'
    restart: 'unless-stopped'
    networks:
      - 'proxy'
      - 'socket_proxy'
      - 'apps'
    security_opt:
      - 'no-new-privileges:true'
    environment:
      DOCKER_HOST: 'tcp://socket-proxy:2375'
      GLANCES_OPT: '-w'
    labels:
      traefik.docker.network: 'proxy'
      traefik.enable: 'true'
      traefik.http.routers.glances.entrypoints: 'websecure'
      traefik.http.routers.glances.rule: 'Host(`glances.$DOMAINNAME`)'
      traefik.http.routers.glances.service: 'glances-svc'
      traefik.http.routers.glances.tls: 'true'
      traefik.http.routers.glances.tls.certresolver: 'wildcard-cloudflare'
      traefik.http.services.glances-svc.loadbalancer.server.port: '61208'
    pid: 'host'
    privileged: true

  # ---------------------------------------------------------------------------- #
  #                     Dozzle - Real-time Docker Log Viewer                     #
  # ---------------------------------------------------------------------------- #
  dozzle:
    container_name: 'dozzle'
    image: 'amir20/dozzle:latest'
    restart: 'unless-stopped'
    networks:
      - 'proxy'
      - 'socket_proxy'
      - 'apps'
    security_opt:
      - 'no-new-privileges:true'
    environment:
      DOCKER_HOST: 'tcp://socket-proxy:2375'
      DOZZLE_FILTER: 'status=running'
      DOZZLE_LEVEL: 'info'
      DOZZLE_TAILSIZE: 300
    labels:
      traefik.enable: 'true'
      traefik.http.routers.dozzle.entrypoints: 'websecure'
      traefik.http.routers.dozzle.rule: 'Host(`dozzle.$DOMAINNAME`)'
      traefik.http.routers.dozzle.service: 'dozzle-svc'
      traefik.http.routers.dozzle.tls: 'true'
      traefik.http.routers.dozzle.tls.certresolver: 'wildcard-cloudflare'
      traefik.http.services.dozzle-svc.loadbalancer.server.port: '8080'
